merged Edward Lee's line anchors patch

diff --git a/tests/test-convert-darcs b/tests/test-convert-darcs
--- a/tests/test-convert-darcs
+++ b/tests/test-convert-darcs
@@ -9,6 +9,14 @@ echo 'hgext.graphlog =' >> $HGRCPATH
 DARCS_EMAIL='test@example.org'; export DARCS_EMAIL
 HOME=do_not_use_HOME_darcs; export HOME
 
+# skip if we can't import elementtree
+mkdir dummy
+mkdir dummy/_darcs
+if hg convert dummy 2>&1 | grep ElementTree > /dev/null; then
+    echo 'skipped: missing feature: elementtree module'
+    exit 80
+fi
+
 echo % initialize darcs repo
 mkdir darcs-repo
 cd darcs-repo
@@ -18,7 +26,7 @@ darcs record -a -l -m p0
 cd ..
 
 echo % branch and update
-darcs get darcs-repo darcs-clone
+darcs get darcs-repo darcs-clone >/dev/null
 cd darcs-clone
 echo c >> a
 echo c > c
@@ -42,7 +50,7 @@ glog()
     hg glog --template '#rev# "#desc|firstline#" files: #files#\n' "$@"
 }
 
-hg convert darcs-repo darcs-repo-hg
+hg convert darcs-repo darcs-repo-hg 2>&1 | grep -v hGetLine | grep -v '^$'
 # The converter does not currently handle patch conflicts very well.
 # When they occur, it reverts *all* changes and moves forward,
 # letting the conflict resolving patch fix collisions.
